# Generated by Django 4.0.3 on 2022-03-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('users', '0002_alter_newuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='favorites',
            field=models.ManyToManyField(blank=True, to='api.noodle'),
        ),
    ]
