# Generated by Django 4.0.3 on 2022-04-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_orderitem_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='cart_items',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
