# Generated by Django 4.0.3 on 2022-04-30 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_order_products_order_cart_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_items',
        ),
    ]
