# Generated by Django 4.0.3 on 2022-04-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_order_cart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_items',
            field=models.JSONField(default=dict),
        ),
    ]
