# Generated by Django 4.0.3 on 2022-05-01 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_order_cart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
    ]
