# Generated by Django 4.0.3 on 2022-05-01 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_order_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='place',
            new_name='country',
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount_without_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
