# Generated by Django 4.0.3 on 2022-05-01 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_place_order_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_amount_without_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
