# Generated by Django 4.0.3 on 2022-04-14 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(null=True, upload_to='noodles_api/brands'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='noodles_api/categories'),
        ),
        migrations.AddField(
            model_name='tags',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='noodleimage',
            name='noodle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgNoodle', to='api.noodle'),
        ),
    ]
