# Generated by Django 4.0.3 on 2022-03-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spicylevel',
            name='slug',
        ),
        migrations.AlterField(
            model_name='noodle',
            name='price_per_package',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='noodle',
            name='price_per_unite',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
