# Generated by Django 4.0.3 on 2022-04-21 03:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_brand_description_brand_image_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spicylevel',
            name='level_number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
