# Generated by Django 4.0.3 on 2022-03-19 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_spicylevel_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noodle',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
