# Generated by Django 4.0.3 on 2022-03-19 04:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_noodle_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noodle',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
