# Generated by Django 4.0.3 on 2022-03-19 04:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_noodle_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='noodle',
            name='UD',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='noodle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
