# Generated by Django 4.0.3 on 2022-03-19 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_noodle_ud_alter_noodle_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noodle',
            name='UD',
        ),
    ]
